#! /bin/sh

# Based on a script by Uli Kusterer
# https://github.com/uliwitness/UliKit/blob/master/make_git_version_header.sh
#
#
#	Copyright 2010 Uli Kusterer.
#	
#	This software is provided 'as-is', without any express or implied
#	warranty. In no event will the authors be held liable for any damages
#	arising from the use of this software.
#
#	Permission is granted to anyone to use this software for any purpose,
#	including commercial applications, and to alter it and redistribute it
#	freely, subject to the following restrictions:
#
#	   1. The origin of this software must not be misrepresented; you must not
#	   claim that you wrote the original software. If you use this software
#	   in a product, an acknowledgment in the product documentation would be
#	   appreciated but is not required.
#
#	   2. Altered source versions must be plainly marked as such, and must not be
#	   misrepresented as being the original software.
#
#	   3. This notice may not be removed or altered from any source
#	   distribution.
#


if [ ! $GIT ]
then
	GIT=git
fi

if [ ! $WC ]
then
	WC=wc
fi

if [ ! $SED ]
then
	SED=sed
fi


if [ ! $TARGET ]
then
	if [ $1 ]
	then
		TARGET=$1
	else
		TARGET="revision.h"
	fi
fi


revnum=`$GIT rev-list HEAD | $WC -l | $SED -e 's/^ *//g;s/ *$//g'`
revhash=`$GIT rev-parse HEAD`
date=`date "+%Y-%m-%d"`


echo "// This file is automatically generated. DO NOT EDIT." > $TARGET
echo "" >> $TARGET
echo "#define REVISION_NUMBER		$revnum" >> $TARGET
echo "#define REVISION_IDENTIFIER	\"$revhash\"" >> $TARGET
echo "#define BUILD_DATE			\"$date\"" >> $TARGET
